package main

// autogenerated by goderive and renamed- some updates were needed
func runEverythingCompose(f0 func() (interface{}, interface{}, error), f1 func(interface{}, interface{}) (interface{}, error), f2 func(interface{}) error) func() error {
	return func() error {
		v_1_0, v_1_1, err0 := f0()
		if err0 != nil {
			return err0
		}
		v_2_0, err1 := f1(v_1_0, v_1_1)
		if err1 != nil {
			return err1
		}
		err2 := f2(v_2_0)
		if err2 != nil {
			return err2
		}
		return nil
	}
}

// autogenerated by goderive and renamed
func fetchDataFromFileCompose(f0 func(string) ([]byte, error), f1 func([]byte) (interface{}, error), f2 func(interface{}) (interface{}, error)) func(string) (interface{}, error) {
	return func(v_0_0 string) (interface{}, error) {
		v_1_0, err0 := f0(v_0_0)
		if err0 != nil {
			return nil, err0
		}
		v_2_0, err1 := f1(v_1_0)
		if err1 != nil {
			return nil, err1
		}
		v_3_0, err2 := f2(v_2_0)
		if err2 != nil {
			return nil, err2
		}
		return v_3_0, nil
	}
}
